<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ertis.Core\Ertis.Core.csproj" />
      <ProjectReference Include="..\Ertis.Data\Ertis.Data.csproj" />
      <ProjectReference Include="..\Ertis.MongoDB.Queries\Ertis.MongoDB.Queries.csproj" />
    </ItemGroup>

</Project>
