<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Ertis.MongoDB</PackageId>
		<PackageVersion>10.0.0</PackageVersion>
		<Version>10.0.0-preview.1</Version>
		<Authors>Ertuğrul Özcan</Authors>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Ertis.Data\Ertis.Data.csproj" />
		<ProjectReference Include="..\Ertis.MongoDB.Queries\Ertis.MongoDB.Queries.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="MongoDB.Driver" Version="3.10.0" />
	</ItemGroup>
</Project>