namespace Ertis.Schema.Types
{
    public enum FieldType
    {
        @object,
        @string,
        integer,
        @float,
        boolean,
        array,
        @enum,
        tags,
        @const,
        json,
        date,
        datetime,
        longtext,
        richtext,
        email,
        uri,
        hostname,
        color,
        location,
        reference,
        code,
        image,
        video
    }
}