<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Ertis.ImageProcessing</PackageId>
		<PackageVersion>10.0.0</PackageVersion>
		<Version>10.0.0-preview.1</Version>
		<Authors>Ertuğrul Özcan</Authors>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Ertis.Core\Ertis.Core.csproj" />
	</ItemGroup>
</Project>