<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Ertis.Extensions.AspNetCore</PackageId>
		<PackageVersion>10.0.1-preview.1</PackageVersion>
		<Version>10.0.1-preview.1</Version>
		<Authors>Ertuğrul Özcan</Authors>
	</PropertyGroup>
	
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Ertis.Core\Ertis.Core.csproj" />
	</ItemGroup>
</Project>