<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Ertis.Core</PackageId>
		<PackageVersion>10.0.2</PackageVersion>
		<Version>10.0.2-preview.1</Version>
		<Authors>Ertuğrul Özcan</Authors>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>
</Project>